version: "0.1"

services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.17.0-community-bullseye
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - "NEO4J_AUTH=none"
    volumes:
      - ./parsed_csv/:/var/lib/neo4j/import/
      - ./data/:/var/lib/neo4j/data/
    #command: tail -F anything
